//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Grammar/Assignment1/Assignment1.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar.Assignment1 {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Assignment1Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IAssignment1Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assignment1Parser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] Assignment1Parser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assignment1Parser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] Assignment1Parser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assignment1Parser.human"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHuman([NotNull] Assignment1Parser.HumanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assignment1Parser.human"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHuman([NotNull] Assignment1Parser.HumanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assignment1Parser.fullName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFullName([NotNull] Assignment1Parser.FullNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assignment1Parser.fullName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFullName([NotNull] Assignment1Parser.FullNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assignment1Parser.nameAge"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameAge([NotNull] Assignment1Parser.NameAgeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assignment1Parser.nameAge"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameAge([NotNull] Assignment1Parser.NameAgeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Assignment1Parser.nameTel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameTel([NotNull] Assignment1Parser.NameTelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Assignment1Parser.nameTel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameTel([NotNull] Assignment1Parser.NameTelContext context);
}
} // namespace Grammar.Assignment1
